- name: Install haproxy
  package:
      name: haproxy
      state: present

- name: Create configuration file
  template:
      src: etc/haproxy/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg

- name: Enable and start haproxy
  systemd:
      name: haproxy
      daemon_reload: true
      state: restarted
      enabled: true
