- name: Install NGINX
  package:
      name: nginx
      state: present

- name: Render configuration
  template:
      src: etc/nginx/nginx.conf.j2
      dest: /etc/nginx/nginx.conf

- name: Enable and start systemd service
  systemd:
      name: nginx
      daemon_reload: true
      enabled: true
      state: restarted
